### ISSUE TITLE
Assign 12

### ISSUE THREAD

**Issue by siriusdemon** [hgzhehe/iub_2009_P523_framework#1]
Hi, I am interesting in this course. I wonder is there an `assign12.pdf` file?

**Comment by hgztheyoung** [comment]
Quick answer is no.
All pdfs availiable on github comes from this repo https://github.com/spiritbear/Grad-School-Code.
It has no assign12.pdf
You may try to conatact those repo owners whether they have assign12.pdf

**Comment by siriusdemon** [comment]
THX
